title: Researchhacking Podcast
url: https://researchhacking.github.io/podcast
baseurl: /podcast
remote_theme: pages-themes/midnight@v0.2.0
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "christian"
plugins:
  - jekyll-remote-theme
  - jekyll-feed
